In [1]:
import torch
import numpy as np



In [6]:
x = torch.tensor([1,1],dtype = torch.float)
y = torch.tensor([1,2],dtype = torch.float)


In [27]:
print(x)
print(x.reshape(-1,1))

tensor([1., 1.])
tensor([[1.],
        [1.]])


In [14]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

tensor([2., 3.])
tensor([ 0., -1.])
tensor([1., 2.])
tensor([1.0000, 0.5000])


In [16]:
a = 1.5
print(a*x)

tensor([1.5000, 1.5000])


In [7]:
x.norm()

tensor(1.4142)

In [8]:
torch.dist(x,y)

tensor(1.)

In [17]:
A = torch.tensor([[1,1],[0,1]],dtype=torch.float)

In [31]:
print(A*y)
print(y*A)

tensor([[1., 2.],
        [0., 2.]])
tensor([[1., 2.],
        [0., 2.]])


In [30]:
print(A*y.reshape(-1,1))
print(y.reshape(-1,1)*A)

tensor([[1., 1.],
        [0., 2.]])
tensor([[1., 1.],
        [0., 2.]])


In [26]:
print(A.mm(x.reshape(-1,1)))

tensor([[2.],
        [1.]])


In [33]:
print(A.inverse())
print(A.inverse().mm(A))

tensor([[ 1., -1.],
        [ 0.,  1.]])
tensor([[1., 0.],
        [0., 1.]])


In [34]:
# ジョルダン系なので
print(A.eig())

torch.return_types.eig(
eigenvalues=tensor([[1., 0.],
        [1., 0.]]),
eigenvectors=tensor([]))
